language: ruby
rbenv:
- 2.5.3
cache:
- bundler
- yarn
addons:
  postgresql: 9.6
before_install:
- gem install bundler
- nvm install --lts
before_script:
- yarn
script:
- bundle exec rake
env:
  global:
    secure:
deploy:
  provider: heroku
  api_key:
    secure: f0N1a4JMH3yWo5BT7fZ5arf0X9r9SV9dICv7WMVZIgu+d3/MpXNmyQ66kquiOHU+O6MW5FFMWVUXzFPj4RCsDdaAh8D0DllfY7yMjyiuicPPx/NrHR+r/uzd8dQYwe/a9+YN7vbiKnt+NQzHLd2TpXIqYSPO/EkfZaSCQpUrTYYNSGRK4YBsAdRVZsJlLGRF3A8AGx3hjOYTZO/k52sDYzYujvxctLN39vDdW+S8IS9Ca9II9eBiKUHP3PHo8CTPk2lX3B0FItpb1Gn5pX0m6ClB1JOVVnAj9l9DhWjwtcXDz/LAdu8FmlKJWktfaLlnyjX4YKsuzI3g/j40YOjLf4zbS2bDfKgEIMczXa3hzdG6LlvjLbb9ZyrCViDNoAsfw+JHQctPp6rXfHwfboIox+xbPx/ekBUBVbqnHzpKNCLTYahOfZdJIs1n4J6ydqY/A+oFz2RP9BVWBlwAsaBXEMlXGAR1PJot9yAOw7AoCW14wp6HyTvQ+dkU67rR90iSKnZ7ZmaAskvOMH94effRdPnMP54lV14nnYywvQZ9NrZdBcGAQN45kWpWLRMbcLjpNjtlnBYSsSL1E6RSyBVgGiKzM6TrLInylEQmNgjQQ/q1yoaMo77qP/a9QvR03EKrOnwssKujj3NBmIwj8u8ZU1bYOl7/uYR8tHDcaiWvvw8=
  app: wine-service-sinatra
  on:
    repo: WeatherVine/wine_service
    branch: main
  skip_cleanup: 'true'
