language: ruby
rbenv:
- 2.5.3
cache:
- bundler
- yarn
addons:
  postgresql: 9.6
before_install:
- gem install bundler
- nvm install --lts
before_script:
- yarn
script:
- bundle exec rake
env:
  global:
    secure:
deploy:
  provider: heroku
  on:
    repo: WeatherVine/wine_service
    branch: main
  skip_cleanup: "‘true’"
  api_key:
    secure: aWqRRAGDEUtxotbMWIOL64mdsWf5KHw+vNaZexrtc6P0MV0udRF2SAFQOgauA8YRkENV1NH5qEZ8istha8z8weE63JYODI3WlWXxurpughQ7is2PlA9FTwpkfzQk46DJO/u0O1kQDvPy8QvaS2GVjbVkI3t10p5QuJkNkypFPht8ITTG++2bR+D8rkouCNNMm1P81dHi2kfggvdb8JYsbLviVTG7jPiw3siJcXC3OTlt4+E9tVKEZ3VBM31pOegMXkyXYEzTyDFMYs+ufwx3vy5QXYEWHnGtRr7gTDmzAQNJEL2MgwrFcBf4T3vvhiXYVT30MVAZJiY9NjMwW2ts2F9hgHELooqxLfG/X5qvDPvZ6lJMjRwc3a4KHKynKLATUGhFfw/kI5sP2nSsWLV+l0uCCNV0voTTUpaHvFVxX4sbVlO3llXDjdY84xpHQsajeyMRJUQJtyB3T+kIbjvbzpeHU2cnEg7RTjkrbln3UZPGQEwpK8KAKNMndga05v21YjVGImEvdmwnQqFljG7aRupyWc3rx9Hwf95gyGGoW73E6Uyd8+StP0DJHL+gdIiQ1Qnjnkx2fTwjsGYa+ep37kiu2WSgLRH37IuV95XRnxzwrcZpf8uzddjK6anL8pUTbh0hiPUJdiHmQFBAb0RZ+ISxkNL7yqqAOK3xRbI8shA=
