language: ruby
rbenv:
- 2.5.3
cache:
- bundler
- yarn
addons:
  postgresql: 9.6
before_install:
- gem install bundler
- nvm install --lts
before_script:
- yarn
script:
- bundle exec rake
env:
  global:
    secure:
deploy:
  provider: heroku
  api_key:
    secure: uihEEmh3dmfykxVrWOA9noUf5zhScVeNOe+QY7ZTOe+BjaCnIDK37lGuPZZAWhqyZjP2YulcBMK2BGuZClIqgnA5W4gpaSfUJu9Ye8uHN+8jc82xadHSaXAqmPpqaNsBKUPXXIbt78PLPaopPFur7+O9yEsqH8fQvu+e9mNVDeG6jpdoyFzXjZMLmzYJLaFqUNcff8DkoZRPLsFwbgburoPjklhrpo+TUKXQ36AjrAjIp7dNfQ8174Vgjg5YxjXqWcflOOlhq92YmQpkr4HPSzgCJMwKTE1aROThRN/YwdrwYm9k+UIXDrrn0yk773+naZZshse6XiUh2Agk5/5nZTS6EfxwrS7wkzJ8D93KeJJaEiMDlsFcfo3H8BLW6ueB/RqtfP6oPuHou9cPtMy8ea4PlHOvgUIx1ZbzNEHFqyWFVm/6R4ZL2ovSTjONolREz0bg+m+3v7/HkgYTeNwErG2xT1+D7LW90izJ5oT7XA+3nfgIkUjZssz8C7lrsRz6mYvQWmBK9mL25SWBWsyCyRUsOlWchLmWmfnFTFm87+3V0p0HwUV8kFJECsURTEtpwBMvflOfvTf8neGep2ff7MrNFPWl/RosbZQHVgjvNOEDihj2NPkU/98fV3fhVst5LsYnwy9rYCNPN2XVqb5G9UsaImPER8w7K8x/SENeg24=
  app: wine-service-sinatra
  on:
    repo: WeatherVine/wine_service
    branch: main
  skip_cleanup: 'true'
